CXXFLAGS=-fPIC -Wall -W -O3 -I.. -I. `python-config --includes` -std=c++11 
LIBS=-lboost_python -lboost_system -lpython -lgsl -lgslcblas 

all: fwdpp_boost_python.o social_evol.o
	$(CXX) -shared -o fwdpp_boost_python.so fwdpp_boost_python.o $(LIBS)
	$(CXX) -shared -o social_evol.so social_evol.o $(LIBS)
