#ifndef __FWDPP_SUGAR_POPTYPES_TAGS_HPP__
#define __FWDPP_SUGAR_POPTYPES_TAGS_HPP__

namespace KTfwd {
  namespace sugar {
    enum class FWDPP_SUGAR_POPTYPE { SINGLE, META, MULTILOC };
    template<FWDPP_SUGAR_POPTYPE> struct FWDPP_SUGAR_POPTAG {};
    using SINGLEPOP_TAG = FWDPP_SUGAR_POPTAG<FWDPP_SUGAR_POPTYPE::SINGLE>;
    using METAPOP_TAG = FWDPP_SUGAR_POPTAG<FWDPP_SUGAR_POPTYPE::META>;
    using MULTILOCPOP_TAG = FWDPP_SUGAR_POPTAG<FWDPP_SUGAR_POPTYPE::MULTILOC>;
  }
}

#endif
